"""After-action report (AAR) generator.

The AAR is deterministic Markdown built from score.json and telemetry.
Optionally, the local Gemma4 model adds a short debrief narrative —
clearly labeled as generated by the local model.
"""

from __future__ import annotations

import json
from pathlib import Path

from . import gemma, telemetry
from .missions import Mission

RECOMMENDATIONS = {
    "mission_completion": "Re-run the mission and work the objective checklist before the clock runs down.",
    "evidence_discipline": "Cite the exact files that support each claim. If you can't point at it, don't assert it.",
    "tool_reliability": "Slow down on tooling: verify each command's output before building on it.",
    "prompt_discipline": "Give the local model specific context (files, constraints) instead of broad questions.",
    "recovery_from_bad_ai_guidance": "When the model's first answer fails a check, trace the evidence before re-prompting.",
    "terminal_recovery": "Practice recovering from failed commands without abandoning the run.",
    "hallucination_resistance": "Treat every unsourced model claim as unverified until you confirm it in the workspace.",
    "time_to_signal": "Find the first strong signal faster: triage the newest logs and diffs first.",
    "communication_quality": "Tighten the final note: lead with the finding, then the evidence, then the action.",
    "local_offline_compliance": "Run against a real local Gemma4 model. Development fallbacks score zero here.",
}


def _fmt_time(seconds: int) -> str:
    return f"{seconds // 60}:{seconds % 60:02d}"


def _bar(points: int, maximum: int, width: int = 20) -> str:
    if maximum <= 0:
        return "·" * width + " n/a"
    filled = round(points / maximum * width)
    return "█" * filled + "·" * (width - filled) + f" {points}/{maximum}"


def generate_aar(mission: Mission, run_dir: Path, narrate: bool = True) -> Path:
    score = json.loads((run_dir / "score.json").read_text())
    events = telemetry.read_events(run_dir)
    asks = [e for e in events if e.get("type") == "ask"]

    grade_pct = round(score["total"] / score["max_total"] * 100) if score["max_total"] else 0
    flags = score.get("flags", {})

    lines: list[str] = []
    lines.append(f"# After-Action Report: {mission.title}")
    lines.append("")
    lines.append(f"- **Operator:** `{score['callsign']}`")
    lines.append(f"- **Run:** `{score['run_id']}`")
    lines.append(f"- **Event:** {mission.event_type.title()} · difficulty {mission.difficulty}/5")
    lines.append(f"- **Score:** **{score['total']} / {score['max_total']}** ({grade_pct}%)")
    lines.append(f"- **Elapsed:** {_fmt_time(score['elapsed_seconds'])}")
    lines.append(f"- **XP awarded:** {score['xp_awarded']}")
    model = score.get("local_model", {})
    model_label = f"{model.get('model', 'unknown')} via {model.get('provider', 'unknown')}"
    if model.get("simulated"):
        model_label += " **TEST FALLBACK (not a real model run)**"
    lines.append(f"- **Local inference:** {model_label}")
    if flags.get("suspicious_fast"):
        lines.append(
            "- **FLAG:** completion time was below this mission's realistic floor. "
            "The run is marked **UNVERIFIED · SUSPICIOUS TIME** and awarded no XP."
        )
    if flags.get("missing_telemetry"):
        lines.append("- **FLAG:** no telemetry log found; decision trace unavailable.")
    lines.append("")

    lines.append("## Objective Checks")
    lines.append("")
    for c in score["checks"]:
        mark = "✅" if c["passed"] else "❌"
        lines.append(f"- {mark} {c['label']} ({c['points']}/{c['max']})")
    lines.append("")

    lines.append("## Readiness Dimensions")
    lines.append("")
    lines.append("```")
    for dim, vals in score["dimensions"].items():
        if vals["max"] == 0:
            continue
        lines.append(f"{dim:32s} {_bar(vals['points'], vals['max'])}")
    lines.append("```")
    lines.append("")

    lines.append("## Decision Trace")
    lines.append("")
    if asks:
        lines.append(f"{len(asks)} exchange(s) with the local model:")
        lines.append("")
        for i, e in enumerate(asks, 1):
            prompt = str(e.get("prompt", ""))[:160]
            response = str(e.get("response", "")).strip().replace("\n", " ")[:220]
            lines.append(f"{i}. **Operator:** {prompt}")
            lines.append(f"   **Local model ({e.get('model')}):** {response}…")
    else:
        lines.append(
            "No local-model exchanges were logged. Either telemetry was off or the "
            "operator never consulted the model."
        )
    lines.append("")

    # Training focus: weakest scored dimensions.
    scored = [
        (dim, vals) for dim, vals in score["dimensions"].items() if vals["max"] > 0
    ]
    scored.sort(key=lambda kv: kv[1]["points"] / kv[1]["max"])
    lines.append("## Training Focus")
    lines.append("")
    weak = [
        (dim, vals) for dim, vals in scored if vals["points"] / vals["max"] < 0.9
    ][:2]
    if weak:
        for dim, vals in weak:
            pct = round(vals["points"] / vals["max"] * 100)
            lines.append(
                f"- **{dim.replace('_', ' ')}** ({pct}%): {RECOMMENDATIONS.get(dim, '')}"
            )
    else:
        lines.append(
            "- No weak dimensions this run. Advance to the next event on the "
            "mission board. The league gets harder from here."
        )
    lines.append("")

    if narrate and not model.get("simulated"):
        try:
            summary_ctx = json.dumps(
                {
                    "mission": mission.title,
                    "score": f"{score['total']}/{score['max_total']}",
                    "elapsed": _fmt_time(score["elapsed_seconds"]),
                    "checks": [
                        {"label": c["label"], "passed": c["passed"]} for c in score["checks"]
                    ],
                    "ask_count": len(asks),
                },
                indent=2,
            )
            out = gemma.ask(
                "Write a 3-sentence after-action debrief for this training run. "
                "Be direct and specific about what went well and what to improve. "
                "Do not invent details not present in the data.",
                context=f"Run summary JSON:\n{summary_ctx}",
            )
            lines.append("## Local Model Debrief")
            lines.append("")
            lines.append(
                f"*Generated locally by {out['model']} ({out['provider']}), "
                "the same offline model used in the mission.*"
            )
            lines.append("")
            lines.append(out["response"].strip())
            lines.append("")
        except gemma.GemmaUnavailable:
            pass

    lines.append("---")
    lines.append(
        "*CyberTrack results are training and readiness feedback for this exercise "
        "only. They are not job-suitability, hiring, or selection signals.*"
    )
    lines.append("")

    aar_path = run_dir / "aar.md"
    aar_path.write_text("\n".join(lines))
    return aar_path
